USE [Reclamacao]
GO

/****** Object:  Index [CLIENTE]    Script Date: 12/03/2026 01:52:25 ******/
CREATE NONCLUSTERED INDEX [CLIENTE] ON [dbo].[TB_Romaneio]
(
	[Cod_Cad_Oid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


USE [Reclamacao]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [data_ent_index]    Script Date: 12/03/2026 01:52:34 ******/
CREATE NONCLUSTERED INDEX [data_ent_index] ON [dbo].[TB_Romaneio]
(
	[Data_Ent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Reclamacao]
GO

/****** Object:  Index [data_entrega_index]    Script Date: 12/03/2026 01:52:47 ******/
CREATE NONCLUSTERED INDEX [data_entrega_index] ON [dbo].[TB_Romaneio]
(
	[Data_Entrega] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Reclamacao]
GO

/****** Object:  Index [data_ped_index]    Script Date: 12/03/2026 01:53:16 ******/
CREATE NONCLUSTERED INDEX [data_ped_index] ON [dbo].[TB_Romaneio]
(
	[Data_Ped] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Reclamacao]
GO

/****** Object:  Index [MOTORISTA]    Script Date: 12/03/2026 01:53:41 ******/
CREATE NONCLUSTERED INDEX [MOTORISTA] ON [dbo].[TB_Romaneio]
(
	[Cod_Mot_Oid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Reclamacao]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [n_ped]    Script Date: 12/03/2026 01:53:59 ******/
CREATE NONCLUSTERED INDEX [n_ped] ON [dbo].[TB_Romaneio]
(
	[N_Ped] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Reclamacao]
GO

/****** Object:  Index [n_seq]    Script Date: 12/03/2026 01:54:20 ******/
CREATE NONCLUSTERED INDEX [n_seq] ON [dbo].[TB_Romaneio]
(
	[N_Seq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [Reclamacao]
GO

/****** Object:  Index [num_rom]    Script Date: 12/03/2026 01:54:34 ******/
CREATE NONCLUSTERED INDEX [num_rom] ON [dbo].[TB_Romaneio]
(
	[Num_Rom] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO




