SELECT FORMS_NF.Forms_nf_oid, FORMS_NF.D_EMISSAO,
CONVERT(MONEY,FORMS_NF.Val_total) VAL_TOTAL, CONVERT(MONEY,valor_icms) VALOR_ICMS, FORMS_NF.NFE_F_expt,
FORMS_NF.NFE_F_IMPORT, FORMS_NF.serie_form, FORMS_NF.Serie, FORMS_NF.NFE_chave,
FORMS_NF.NFE_protocolo,
NOTAFIS.NO_NOTA,
CABE_PED.No_PED, CABE_PED.FASE, CAD_CLI.NOME, C5.C5_NUM, C6_NOTA, C6_SERIE, CONVERT(MONEY,VALOR-C5.C5_DESCONT+C5.C5_FRETE) VALOR, CONVERT(MONEY,F2_VALICM) F1_VALICM, EXP_MSG,
CAD_FUNC_AC.APELIDO, D1_DOC,
CASE 
	WHEN FORMS_NF.NFE_F_expt = 0 AND FORMS_NF.Cancelado = 0 THEN 1
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NULL) THEN 2
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NOT NULL) AND (EXP_SC5.API_STAT = 'N') AND (EXP_SC5.F_RET = 0) THEN 3
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NOT NULL) AND (EXP_SC5.API_STAT = 'N') AND (EXP_SC5.F_OK = 0) THEN 4
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NOT NULL) AND (EXP_SC5.API_STAT = 'N') AND (EXP_SC5.F_OK = 1) THEN 5
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NOT NULL) AND (EXP_SC5.F_RET = 0) THEN 9
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NOT NULL) AND (EXP_SC5.API_STAT = 'P') THEN 10
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 0 AND (EXP_SC5.C5_XFORMS IS NOT NULL) AND (EXP_SC5.API_STAT = 'E') THEN 4
	WHEN FORMS_NF.NFE_F_expt = 1 AND FORMS_NF.NFE_F_IMPORT = 1 AND FORMS_NF.Cancelado = 0 AND (D1_DOC IS NULL) THEN 6
	WHEN FORMS_NF.Cancelado = 1 THEN 7
	WHEN (D1_DOC IS NOT NULL) AND LTRIM(RTRIM(D1_DOC)) <> '' THEN 8
	WHEN ERROS > 0 THEN 2
END STAT,
CASE 
	WHEN (CONVERT(MONEY,FORMS_NF.Val_total) <> CONVERT(MONEY,VALOR-C5.C5_DESCONT+C5.C5_FRETE)) AND (EXP_SC5.F_OK = 1) THEN 'VALOR TOTAL DIVERGENTE ENTRE DIS E PROTHEUS' 	
	WHEN (CONVERT(MONEY,FORMS_NF.valor_icms) <> CONVERT(MONEY,F2_VALICM)) AND (EXP_SC5.F_OK = 1) THEN 'VALOR DE ICMS DIVERGENTE ENTRE DIS E PROTHEUS' 
END 'DIVERGENCIA', 
CONVERT(BIT,0) AS PED_CLI_OK, 'NÃO' AS PED_CLI_OK_DESC,
FORMS_NF.C6_LOCAL,
VW_ROM.Motorista, VW_ROM.Num_Rom, VW_ROM.N_SEQ
--INTO #NOTAS
FROM FORMS_NF
left join NOTAFIS ON FORMS_NF.Notafis_oid = NOTAFIS.Notafis_oid
LEFT JOIN NAT_OPER ON NOTAFIS.NAT_OPER_OID = NAT_OPER.NAT_OPER_OID
LEFT JOIN CABE_PED ON FORMS_NF.Notafis_oid = CABE_PED.Notafis_oid
LEFT JOIN CAD_FUNC AS CAD_FUNC_AC ON CABE_PED.AC_CAD_FUNC_OID = Cad_func_AC.Cad_func_oid
LEFT JOIN CAD_CLI ON CABE_PED.CAD_CLI_OID = CAD_CLI.CAD_CLI_OID
LEFT JOIN (SELECT FORMS_NF_OID, COUNT(*) ERROS FROM EXP_ERRO GROUP BY FORMS_NF_OID) TB_ERROS ON FORMS_NF.Forms_nf_oid = TB_ERROS.FORMS_NF_OID
LEFT JOIN EXP_COND_PG ON CABE_PED.COND_PG_OID = EXP_COND_PG.COND_PG_OID
LEFT JOIN EXP_SC5 ON FORMS_NF.Forms_nf_oid = EXP_SC5.C5_XFORMS
LEFT JOIN PontualSQL.dbo.cad_grupo ON cad_cli.cad_grupo_oid = cad_grupo.cad_grupo_oid
LEFT JOIN SRV30.TOP12_OFICIAL.dbo.SC5010 C5 WITH (NOLOCK) ON FORMS_NF.Forms_nf_oid = C5.C5_XFORMS AND C5.D_E_L_E_T_ = ''
LEFT JOIN (SELECT C6_NUM, C6_NOTA, C6_SERIE, SUM(C6_VALOR) VALOR FROM SRV30.TOP12_OFICIAL.dbo.SC6010 WITH (NOLOCK) WHERE D_E_L_E_T_ = '' GROUP BY C6_NUM, C6_NOTA, C6_SERIE) C6
	ON C5.C5_NUM = C6_NUM
LEFT JOIN (SELECT F2_DOC, F2_SERIE, F2_VALICM FROM SRV30.TOP12_OFICIAL.dbo.SF2010 WITH (NOLOCK) WHERE D_E_L_E_T_ = '') F2 
	ON C6_NOTA = F2_DOC
	AND C6_SERIE = F2_SERIE
LEFT JOIN VW_ROM
    ON CABE_PED.No_PED = VW_ROM.NO_PED
LEFT JOIN (
	SELECT DISTINCT D1_SERIE, D1_DOC, D1_NFORI, D1_SERIORI, D1_TIPO
	FROM SRV30.TOP12_OFICIAL.dbo.SD1010 SD1 WITH (NOLOCK)
	WHERE D1_FORMUL = 'S'
	AND D_E_L_E_T_ = ' '
	AND D1_NFORI <> ''
	AND D1_TIPO IN ('D','B')
	AND D1_SERIE <> 'OUT'
	) DEVOLUCAO
	ON F2_SERIE + F2_DOC = D1_SERIORI + D1_NFORI
WHERE FORMS_NF.f_nfiscal = 0
AND NOTAFIS.D_VENCTO IS NOT NULL
 AND FORMS_NF.D_EMISSAO BETWEEN '2026-03-11' AND '2026-03-12'
 AND NAT_OPER.F_VENDA = 1