CREATE VIEW VW_ICMS AS (

SELECT D2_FILIAL, D2_DOC, D2_SERIE, 
CONVERT(MONEY,SUM( CASE WHEN D2_CLASFIS IN ('010','020','030') THEN D2_VALICM ELSE 0 END)) AS ICMS_TRIB,
CONVERT(MONEY,SUM( CASE WHEN D2_CLASFIS NOT IN ('010','020','030') THEN D2_VALICM ELSE 0 END)) AS ICMS_NAO_TRIB,
CONVERT(MONEY,SUM(D2_VALICM)) AS ICMS_TOT
FROM SD2010 SD2
JOIN SF2010 SF2
ON SD2.D2_FILIAL = F2_FILIAL
AND SD2.D2_DOC = SF2.F2_DOC
AND D2_SERIE = F2_SERIE
AND SF2.D_E_L_E_T_ = ' '
WHERE SD2.D_E_L_E_T_ = ' '
GROUP BY D2_FILIAL, D2_DOC, D2_SERIE

)