USE [TSS_HOM]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20200120-182334]    Script Date: 10/12/2025 21:09:03 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20200120-182334] ON [dbo].[SPED054]
(
	[NFE_ID] ASC,
	[ID_ENT] ASC,
	[NFE_CHV] ASC,
	[NFE_PROT] ASC,
	[LOGID] ASC,
	[D_E_L_E_T_] ASC,
	[R_E_C_N_O_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

