USE [TSS_HOM]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20200120-182403]    Script Date: 10/12/2025 21:09:24 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20200120-182403] ON [dbo].[SPED054]
(
	[NFE_CHV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

