BACKUP DATABASE [TOP12_OFICIAL] 
TO  DISK = N'O:\Guilherme\TOP12_OFICIAL_20260331.bak' 
WITH NOFORMAT, 
NOINIT,  
NAME = N'TOP12_OFICIAL-Completo Banco de Dados Backup', 
SKIP, 
NOREWIND, 
NOUNLOAD,  
STATS = 10
GO
