SELECT X3_BROWSE, X3_VISUAL, X3_OBRIGAT, X3_CBOX, *
FROM SX3010
WHERE X3_ARQUIVO IN ('SC5','SC6')
AND X3_PROPRI = 'U'

AND X3_CAMPO IN (
'C5_XNPED',
'C5_XTIPO',
'C5_XENDENT',
'C5_XFORMS',
'C5_XSEPARA',
'C6_XCPROD',
'C6_XFORMS',
'C6_XIITNF')