/*

ZAF_STAT 1=Pendente;2=Ignorado;3=Erro;4=Concluido
API_STAT P=Pendente;E=Erro;C=Concluído;N=Não usa API

*/

SELECT C5_OID,

CASE 
WHEN ZAF_ERROR = 1 THEN 'E'
WHEN ZAF_STAT = '4' THEN 'C'
ELSE 'P'
END AS STAT,

CASE 
WHEN ZAF_ERROR = '1' THEN COALESCE(ZAF_MSG,'')
WHEN ZAF_STAT = '4' THEN 'Pedido copiado'
WHEN ZAF_STAT = '2' THEN 'Ignorado'
WHEN ZAF_STAT = '1' THEN 'Processamento pendente'
ELSE ''
END AS MSG

FROM EXP_SC5
JOIN TOP12_HOM2410.dbo.ZAF010 ZAF
ON EXP_SC5.C5_FILIAL COLLATE Latin1_General_BIN = ZAF_FILIAL
AND EXP_SC5.C5_XFORMS = ZAF_XFORMS
WHERE API_STAT = 'P'
AND C5_EMISSAO >= GETDATE()-10

